/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MarketPricesRouteImport } from './routes/market-prices'
import { Route as PriceTrendsRouteImport } from './routes/price-trends'
import { Route as MarketIdRouteImport } from './routes/market.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketPricesRoute = MarketPricesRouteImport.update({
  id: '/market-prices',
  path: '/market-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceTrendsRoute = PriceTrendsRouteImport.update({
  id: '/price-trends',
  path: '/price-trends',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/market/$id',
  path: '/market/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/market-prices': typeof MarketPricesRoute
  '/price-trends': typeof PriceTrendsRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/market-prices': typeof MarketPricesRoute
  '/price-trends': typeof PriceTrendsRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/market-prices': typeof MarketPricesRoute
  '/price-trends': typeof PriceTrendsRoute
  '/market/$id': typeof MarketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/market-prices' | '/price-trends' | '/market/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/market-prices' | '/price-trends' | '/market/$id'
  id: '__root__' | '/' | '/market-prices' | '/price-trends' | '/market/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketPricesRoute: typeof MarketPricesRoute
  PriceTrendsRoute: typeof PriceTrendsRoute
  MarketIdRoute: typeof MarketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-prices': {
      id: '/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof MarketPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-trends': {
      id: '/price-trends'
      path: '/price-trends'
      fullPath: '/price-trends'
      preLoaderRoute: typeof PriceTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/market/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketPricesRoute: MarketPricesRoute,
  PriceTrendsRoute: PriceTrendsRoute,
  MarketIdRoute: MarketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
